{
  "hash": "d74ddffe186d6b9d9f376cf1dc587c07",
  "result": {
    "markdown": "---\ntitle: \"Time series analysis of nitrogen and phosphorus concentrations in Chesapeake Bay tidal regions since 2010 introduction of TMDL requirements\"\ndescription: \"This analysis seeks to better understand the seasonality of nitrogen and phosphorus concentration in Chesapeake Bay tidal regions, in addition to any non-seasonal trends over the last decade.\"\nauthor: \n  - name: Linus Ghanadan\n    url: https://linusghanadan.github.io/\n    affiliation: MEDS\n    affiliation-url: https://bren.ucsb.edu/masters-programs/master-environmental-data-science\ndate: 12-12-2023\ncategories: [Statistics]\nbibliography: stats_blog.bib\ncitation:\n  url: https://linusghanadan.github.io/blog/2023-12-12-post/\nimage: chesapeake-bay.jpeg\ndraft: false\nformat:\n    html:\n        code-fold: true\n---\n\n\n## Question\n\nSince the 2010 introduction of TMDL requirements, what seasonal and non-seasonal trends are present for nitrogen and phosphorus concentrations in Chesapeake Bay tidal regions?\n\n## Introduction\n\nIn December 2010, the EPA took an unprecedented step in enacting federal policy specific to the Chesapeake Bay, the largest estuary in the United States [@us_environmental_protection_agency_chesapeake_2023]. Specifically, the EPA established Total Maximum Daily Load (TMDL) requirements for the amount of nitrogen, phosphorus, and sediment that is allowed in the Bay. Nitrogen and phosphorus are the two pollutants primarily responsible for algal blooms, which cause marine dead zones through taking in dissolved oxygen and blocking sunlight. Sediment also contributes to dead zones by blocking sunlight, leading it to be included in the 2010 TMDL requirements.\n\nThis analysis will focus on nitrogen and phosphorus, the two nutrient pollutants regulated under the 2010 TMDL requirements. A 2022 study found that agricultural runoff was the largest source of nutrient pollution, accounting for 48% of nitrogen and 27% of phosphorus in the Chesapeake Bay [@chesapeake_progress_2025_nodate]. Both of these pollutants also get to the Bay as a result of urban and suburban runoff, wastewater treatment plants releasing treated water, and natural sources (i.e., runoff from forests, wetlands, etc.). In addition, about 25% of nitrogen that ends up in the Bay comes from air pollution that is originally emitted to the atmosphere by sources such as cars and factories [@burns_atmospheric_2021]. Through a process called atmospheric deposition, these nitrogen compounds react with other chemicals to become nitrous oxides, which can be deposited back to Earth's surface through precipitation or as dry deposition.\n\nThrough conducting a time series analysis of post-2010 nitrogen and phosphorus concentration measurements, my goal is to better understand how concentrations have changed since the introduction of TMDL requirements. I'm also interested in the nature of any seasonality and whether the three time series components (i.e., seasonal, trend, and random) are consistent across both nitrogen and phosphorus.\n\n## Data\n\nYearly water quality data on the Chesapeake Bay's tidal and non-tidal regions going back to 1984 is publicly available on the Chesapeake Bay Program DataHub [@chesapeake_bay_program_datahub_traditional_nodate]. Data is organized into either Tier 1, 2, or 3 depending on how it was collected. While Tier 1 and 2 data can be collected by any interested group, Tier 3 data is collected by monitoring stations overseen by experienced professionals. Only Tier 3 data can be used for governmental regulatory assessments.\n\nFor my analysis, I will be using 2010 to 2019 Tier 3 data collected at 143 different monitoring stations positioned throughout the Chesapeake Bay tidal regions, which includes the mainstem Bay and tributary components. Across the 10 years that we are looking at, we'll have a total of 43,809 nitrogen observations and 43,590 phosphorus observations.\n\nBelow, we import the R packages used in this analysis. Then, we read in the yearly water quality data using their CBP DataHub URL. We also process the data by creating separate data.frames for total nitrogen and phosphorus measurements.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import necessary R packages\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(tsibble)\nlibrary(feasts)\nlibrary(generics)\n\n# Create a vector of data URLs\nexcel_urls <- c(\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2019_CEDR_tidal_data_01jun21.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2018_CEDR_tidal_data_01jun21.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2017_CEDR_tidal_data_11oct18.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2016_CEDR_tidal_data_15jun17.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2015_CEDR_tidal_data_15jun17.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2014_CEDR_tidal_data_15jun17.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2013_CEDR_tidal_data_15jun17.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2012_CEDR_tidal_data_15jun17.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2011_CEDR_tidal_data_15jun17.xlsx',\n  'https://datahub-content.chesapeakebay.net/traditional_annual_tidal_02jun21/2010_CEDR_tidal_data_15jun17.xlsx')\n\n# Create a temporary directory to store downloaded files\ntemp_dir <- tempdir()\n\n# Create an empty list to store data frames\ndfs <- list()\n\n# Loop through each URL, extract file name, define local file path, download file, read into R, and append to list of data frames\nfor (url in excel_urls) {\n  file_name <- basename(url)\n  local_path <- file.path(temp_dir, file_name)\n  download.file(url, destfile = local_path, mode = \"wb\")\n  wq_data <- readxl::read_excel(local_path, sheet = 1)\n  dfs[[file_name]] <- wq_data\n}\n\n# Combine all data frames into a single data frame\nwq_data_combined <- bind_rows(dfs)\n\n# Wrangle data for relevant column variables, and filter for TN (total nitrogen)\nnitr_data <- wq_data_combined %>%\n  dplyr::select(\"MonitoringLocation\", \"SampleDate\", \"Parameter\", \"MeasureValue\", \"Unit\", \"Latitude\", \"Longitude\") %>% \n  filter(Parameter==\"TN\")\n\n# Wrangle data for relevant column variables, and filter for TP (total phosphorus)\nphos_data <- wq_data_combined %>%\n  dplyr::select(\"MonitoringLocation\", \"SampleDate\", \"Parameter\", \"MeasureValue\", \"Unit\", \"Latitude\", \"Longitude\") %>% \n  filter(Parameter==\"TP\")\n\n# Remove unnecessary data and values from environment\nrm(wq_data, wq_data_combined, dfs)\nrm(excel_urls, file_name, local_path, temp_dir, url)\n```\n:::\n\n\n## Exploratory analysis\n\nTo get an idea of what is going on with the data, we'll first calculate moving averages for each year-month, storing as both a tsibble and data.frame. We'll plot these moving averages just to get a general idea of what types of trends we might be looking at.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute nitrogen monthly moving average, and store as tsibble\nnitr_monthly_avgs_ts <- nitr_data %>% \n  mutate(yr_mo = tsibble::yearmonth(SampleDate)) %>%\n  group_by(yr_mo) %>%\n  summarize(monthly_avg = mean(MeasureValue, na.rm = TRUE)) %>% \n  tsibble::as_tsibble()\n\n# Create data frame version, and convert year-months to Date class (helpful for plotting)\nnitr_monthly_avgs_df <- as.data.frame(nitr_monthly_avgs_ts)\nnitr_monthly_avgs_df$yr_mo <- as.Date(nitr_monthly_avgs_ts$yr_mo, format = \"%Y-%m\")\n\n# Plot monthly average nitrogen concentration as a function of year-month\nnitr_monthly_avgs_df %>%\n  ggplot(aes(x = yr_mo, y = monthly_avg)) +\n  stat_summary(geom = 'line', fun = 'mean') +\n  labs(x = 'Year-Month', y = 'Monthly Mean Concentration (mg/L)', title = \"Nitrogen in Chesapeake Bay (2010-2019)\") +\n  scale_x_date(date_breaks = \"1 year\", date_minor_breaks = \"6 months\", date_labels = \"%Y-%m\") +\n  theme_bw() +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nFrom this plot, there does appear to be a seasonal trend for nitrogen concentrations, but there is no clear non-seasonal trend. In addition, there is a notable spike in early 2014.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute phosphorus monthly moving average, and store as tsibble\nphos_monthly_avgs_ts <- phos_data %>% \n  mutate(yr_mo = tsibble::yearmonth(SampleDate)) %>%\n  group_by(yr_mo) %>%\n  summarize(monthly_avg = mean(MeasureValue, na.rm = TRUE)) %>% \n  tsibble::as_tsibble()\n\n# Create data frame version, and convert year-months to Date class (helpful for plotting)\nphos_monthly_avgs_df <- as.data.frame(phos_monthly_avgs_ts)\nphos_monthly_avgs_df$yr_mo <- as.Date(phos_monthly_avgs_ts$yr_mo, format = \"%Y-%m\")\n\n# Plot monthly average phosphorus concentration as a function of year-month\nphos_monthly_avgs_df %>%\n  ggplot(aes(x = yr_mo, y = monthly_avg)) +\n  stat_summary(geom = 'line', fun = 'mean') +\n  labs(x = 'Year-Month', y = 'Monthly Mean Concentration (mg/L)', title = \"Phosphorus in Chesapeake Bay (2010-2019)\") +\n  scale_x_date(date_breaks = \"1 year\", date_minor_breaks = \"6 months\", date_labels = \"%Y-%m\") +\n  theme_bw() +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nSimilar to the nitrogen plot, phosphorus also seems to exhibit a distinct seasonal trend. Again, it also is unclear whether there is non-seasonal trend.\n\n## Methods\n\n#### Autocorrelation function\n\nThe autocorrelation function calculates the correlation between the dependent variable at a given point in time and various time lags for this same variable. For us, the autocorrelation will provide us with a useful glimpse into the nature of the seasonality going on with nitrogen and phosphorus concentrations.\n\n#### STL decomposition\n\nAs a core part of this time series analysis, I'll be constructing a seasonal-trend decomposition using locally estimated scatterplot smoothing (LOESS), which is often abbreviated as a STL decomposition model. STL allows us to separate our monthly average concentrations into three components: seasonal trend, non-seasonal trend, and remainder. Through plotting these components next to each other, we gain a more intuitive understanding on the underlying forces contributing to variation in our dependent variable, which in this case is the monthly average concentration.\n\nAs opposed to other decomposition methods, one thing that is particular to STL models is the ability to specify the length of a season. It can be helpful to adjust this input depending on our desired level of smoothing for the non-seasonal trend. We will use our results from the autocorrelation function to inform our chosen length of seasons. The autocorrelation function is useful in this context because it can tell us after how many lags we see a drop-off in correlation, indicating there is a drop in the significance of the seasonal trend.\n\n## Results\n\n#### Autocorrelation function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot autocorrelation function for nitrogen with lags going back three years\nacf(nitr_monthly_avgs_ts, lag.max = 36, i=2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nLooking at this autocorrelation plot for nitrogen, I see that the *t-16* lag is significant at the alpha equals 0.05 level, indicated by the black line extending beyond the blue dashed line. Meanwhile, the *t-4* lag is not statistically significant. The rest of the lags remain the same or slightly decrease when comparing from the first and second year of lags. In the third year, there is a drop off in the *t-28* lag compared to *t-12*, and there continues to be what seems like a marginal decrease in correlation across most lags. Considering all of this, I decided to set the seasonality of my STL model for nitrogen to 24 months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot autocorrelation function for phosphorus with lags going back three years\nacf(phos_monthly_avgs_ts, lag.max = 36, i = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nFor phosphorus, there is a very consistent marginal decline for each set of lags over the course of the three years. This is good news for our STL because it means that the seasonal trend will be easier to separate from the non-seasonal trend. Like I did with nitrogen, I'm also going to use two-year seasons for phosphorus. Similar to the case with nitrogen, it seems to me like the drop-off in lag correlations from year two to year three is a bit larger than from year one to year two. This suggests that a two-year seasonal cycle will give us an informative nonseasonal-trend component that is neither too eager nor too hesitant to categorize differences as trends.\n\n#### STL decomposition\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Conduct STL time series analysis for nitrogen with two-year seasons, and extract components\nnitr_decomp <- nitr_monthly_avgs_ts %>%\n  fabletools::model(feasts::STL(monthly_avg, t.window = 24)) %>% \n  generics::components()\n\n# Plot STL time series analysis of nitrogen concentration\nautoplot(nitr_decomp) +\n  labs(title = \"STL Time Series Analysis of Nitrogen Concentration\", x = \"Year Month\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nIn this plot of the three STL components for nitrogen, it is still difficult to see a long-term trend, despite the line being fairly smooth. There does seem to be a slight downward trend until around 2018 things really begin increasing. In addition the grey bars on the left all represent the same range, implying that the remainder components contributed the most to nitrogen concentration. However, this seems to be very influenced by the high spike in 2014.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Conduct STL time series analysis for phosphorus with two-year seasons, and extract components\nphos_decomp <- phos_monthly_avgs_ts %>%\n  fabletools::model(feasts::STL(monthly_avg, t.window = 24)) %>% \n  generics::components()\n\n# Plot STL time series analysis\nautoplot(phos_decomp) +\n  labs(title = \"STL Time Series Analysis of Phosphorus Concentration\", x = \"Year Month\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe STL plot for phosphorus does make it seem like there is a long-term downward trend, but it is difficult to tell how significant it is because of the long grey bar, which indicates it is least influential of the three components. In this case, the grey bars show us that seasonality contributes the most to the variation in phosphorus concentration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For nitrogen, plot monthly mean, seasonally adjusted monthly mean, STL seasonality, and STL trend\nggplot(nitr_monthly_avgs_df, aes(yr_mo)) +\n  scale_x_date(date_breaks = \"1 year\", date_minor_breaks = \"6 months\", date_labels = \"%Y-%m\") +\n  geom_line(aes(y=nitr_decomp$monthly_avg, color = \"Monthly mean\")) +\n  geom_line(aes(y=nitr_decomp$season_adjust, color = \"Seasonally adjusted monthly mean\"), linewidth=2) +\n  geom_line(aes(y=nitr_decomp$trend, color = \"STL trend\"), linewidth = 2) +\n  geom_line(aes(y=nitr_decomp$season_year, color = \"STL seasonality\")) +\n  labs(x = 'Year-Month',\n       y = 'Concentration (mg/L)',\n       title = \"Nitrogen in Chesapeake Bay (2010-2019)\") +\n  scale_color_manual(name = \"\", values = c(\"Monthly mean\" = \"black\", \"Seasonally adjusted monthly mean\" = \"cornflowerblue\", \"STL seasonality\" = \"seagreen\", \"STL trend\" = \"red\"), breaks = c(\"Monthly mean\", \"Seasonally adjusted monthly mean\", \"STL seasonality\", \"STL trend\")) +\n  theme_bw() +\n  theme(legend.position = \"top\", plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nI decided to make this visualization to get a better idea of exactly how these components map on to each other. This plot seems to confirm the idea of negligible trend for nitrogen. Since the x-axis is labeled for each year here, it is also easier to see the seasonal trend. Each year, nitrogen concentrations increase sharply around December. They then peak around February to March, before decreasing substantially and reaching their minimum around July.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For phosphorus, plot monthly mean, seasonally adjusted monthly mean, STL seasonality, and STL trend\nggplot(phos_monthly_avgs_df, aes(yr_mo)) +\n  scale_x_date(date_breaks = \"1 year\", date_minor_breaks = \"6 months\", date_labels = \"%Y-%m\") +\n  geom_line(aes(y=phos_decomp$monthly_avg, color = \"Monthly mean\")) +\n  geom_line(aes(y=phos_decomp$season_adjust, color = \"Seasonally adjusted monthly mean\"), linewidth=2) +\n  geom_line(aes(y=phos_decomp$trend, color = \"STL trend\"), linewidth = 2) +\n  geom_line(aes(y=phos_decomp$season_year, color = \"STL seasonality\")) +\n  labs(x = 'Year-Month',\n       y = 'Concentration (mg/L)',\n       title = \"Phosphorus in Chesapeake Bay (2010-2019)\") +\n  scale_color_manual(name = \"\", values = c(\"Monthly mean\" = \"black\", \"Seasonally adjusted monthly mean\" = \"cornflowerblue\", \"STL seasonality\" = \"seagreen\", \"STL trend\" = \"red\"), breaks = c(\"Monthly mean\", \"Seasonally adjusted monthly mean\", \"STL seasonality\", \"STL trend\")) +\n  theme_bw() +\n  theme(legend.position = \"top\", plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nOur plot for phosphorus further supports the idea that there is a slight downward trend over the ten years. If you independently trace the maximums or minimums, the line does seem to be moving downward at an oscillating but fairly consistent rate. Unlike nitrogen, phosphorus concentrations shoot up in the middle of the year around May, have a relatively flat peak lasting from June to August, and then shoot down at the end of Summer.\n\n#### Simple linear regressions based on STL model parameters\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run regression of season component on monthly average nitrogen\nnitr_season_reg <- lm(monthly_avg ~ season_year, data = nitr_decomp)\nsummary(nitr_season_reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = monthly_avg ~ season_year, data = nitr_decomp)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.28803 -0.07036 -0.01624  0.04451  0.50728 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.89766    0.01029   87.26   <2e-16 ***\nseason_year  1.03839    0.08624   12.04   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1127 on 118 degrees of freedom\nMultiple R-squared:  0.5513,\tAdjusted R-squared:  0.5475 \nF-statistic:   145 on 1 and 118 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nAdjusted R-squared of 0.55 indicates that seasonal trends can explain a bit over half (55%) of the variation in nitrogen monthly mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run regression of season component on monthly average phosphorus\nphos_season_reg <- lm(monthly_avg ~ season_year, data = phos_decomp)\nsummary(phos_season_reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = monthly_avg ~ season_year, data = phos_decomp)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0144318 -0.0031716 -0.0003977  0.0037799  0.0156940 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.0565260  0.0005042  112.11   <2e-16 ***\nseason_year 0.9844122  0.0511039   19.26   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.005523 on 118 degrees of freedom\nMultiple R-squared:  0.7587,\tAdjusted R-squared:  0.7567 \nF-statistic: 371.1 on 1 and 118 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nFor phosphorus, adjusted R-squared of this regression is 0.76, confirming our idea that seasonality is more pronounced with phosphorus.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run regression of year-month on trend component for nitrogen\nnitr_trend_reg <- lm(trend ~ yr_mo, data = nitr_decomp)\nsummary(nitr_trend_reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = trend ~ yr_mo, data = nitr_decomp)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.084653 -0.045620 -0.000179  0.032870  0.135876 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.121e+00  7.856e-02  14.268  < 2e-16 ***\nyr_mo       -1.365e-05  4.775e-06  -2.859  0.00502 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05514 on 118 degrees of freedom\nMultiple R-squared:  0.0648,\tAdjusted R-squared:  0.05687 \nF-statistic: 8.176 on 1 and 118 DF,  p-value: 0.005022\n```\n:::\n\n```{.r .cell-code}\n# Compute the confidence interval for the coefficient of yr_mo\n# Multiply by 120 to estimate trend over 10 years\nnitr_trend_10_yr <- 120 * confint(nitr_trend_reg, \"yr_mo\")\ncat('nitr_trend_10_yr:', signif(nitr_trend_10_yr, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnitr_trend_10_yr: -0.00277 -0.000504\n```\n:::\n\n```{.r .cell-code}\n# Convert to percent change since January 2010 observation\nnitr_percent_trend_10_yr <- (nitr_trend_10_yr / nitr_decomp$monthly_avg[1]) * 100\ncat('\\nnitr_percent_trend_10_yr:', signif(nitr_percent_trend_10_yr, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nnitr_percent_trend_10_yr: -0.237 -0.043\n```\n:::\n:::\n\n\nIn this linear regression, we look at the influence of year-month on our non-seasonal trend component for nitrogen. The regression output tells us that we can say at an alpha equals 0.01 significance level that the 10-year non-seasonal trend component is negative. However, the low adjusted R-squared also tells us that variation in year-month explains very little of the variation in trend component. Then, the first interval tells us that there is a 95% chance that the interval from -0.00277 mg/L to -0.000504 mg/L contains the true 10-year non-seasonal trend component. The second interval is telling us that this represents a -0.237% to -0.043% change as compared to the monthly average in January 2010.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run regression of year-month on trend component for phosphorus\nphos_trend_reg <- lm(trend ~ yr_mo, data = phos_decomp)\nsummary(phos_trend_reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = trend ~ yr_mo, data = phos_decomp)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0054726 -0.0011369 -0.0002914  0.0014229  0.0039014 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  9.174e-02  2.858e-03   32.10   <2e-16 ***\nyr_mo       -2.150e-06  1.737e-07  -12.38   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.002006 on 118 degrees of freedom\nMultiple R-squared:  0.5649,\tAdjusted R-squared:  0.5612 \nF-statistic: 153.2 on 1 and 118 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# Compute the confidence interval for the coefficient of yr_mo\n# Multiply by 120 to estimate trend over 10 years\nphos_trend_10_yr <- 120 * confint(phos_trend_reg, \"yr_mo\")\ncat('phos_trend_10_yr:', signif(phos_trend_10_yr, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nphos_trend_10_yr: -0.000299 -0.000217\n```\n:::\n\n```{.r .cell-code}\n# Convert to percent change since January 2010 observation\nphos_percent_trend_10_yr <- (phos_trend_10_yr / phos_decomp$monthly_avg[1]) * 100\ncat('\\nphos_percent_trend_10_yr:', signif(phos_percent_trend_10_yr, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nphos_percent_trend_10_yr: -0.524 -0.38\n```\n:::\n:::\n\n\nFor phosphorus, the linear regression output tells us that we are confident at the alpha equals 0.01 level that the 10-year non-seasonal trend component was negative. It is also worth noting that the adjusted R-squared tells us that over half (56%) of the the variation in trend component can be explained by variation in year-month. Lastly, we find that there is a 95% chance that the interval between -0.000299 mg/L and -0.000217 mg/L contains the true 10-year non-seasonal trend component. This represents a -0.524% to -0.380% change as compared to the monthly average in January 2010.\n\n## Conclusion\n\nMy time series analysis suggests that seasonality plays a substantial role in contributing to variation in the monthly mean concentration of nitrogen and phosphorus in tidal regions of the Chesapeake Bay. For nitrogen, seasonal trends explained 55% of the variation in monthly means, and the relationship was even stronger for phosphorus, with seasonal-trends explaining 76% of the variation. While the seasonal component for nitrogen was highest during Winter, the seasonal component for phosphorus was highest during Summer.\n\nThis analysis was also interested in any non-seasonal trend that has occurred since the introduction of TMDL requirements in 2010. For both nitrogen and phosphorus, we find evidence at an alpha level of 0.01 that the 10-year non-seasonal trend is negative. However, our confidence intervals suggest that such trends represent a less than 1% decrease in concentration over the course of the 10 years for both nutrient pollutants. It was also notable how the non-seasonal trend was much more consistent for phosphorus than nitrogen, as this can be seen in our STL visualization and is also reflected by the larger adjusted R-squared phosphorus (0.56) compared to nitrogen (0.06) computed in the linear regression of non-seasonal trend against year-month.\n\nThe main limitation of this analysis was that no form of spatial interpolation was employed to estimate concentrations across the tidal region based on location of measurements. It would be interesting to compare such an analysis to what we did here, as a significant differences might indicate that sampled areas are not spread throughout the region in a representative manner. Further analysis might also investigate what happened at the beginning of 2014 that could have led to the high spike in nitrogen levels at that time, in addition to factors that might have fueled the gradual increase seen over the course of 2018.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}