{
  "hash": "512840a2a9b745caddb781db9327b030",
  "result": {
    "markdown": "---\ntitle: \"Using propensity score methods to analyze the impact of catch shares policy\"\ndescription: \"Disclaimer: The data used in this blog was synthetically generated (i.e., data is fake so results have no real implications).\"\nauthor: \n  - name: Linus Ghanadan\n    url: https://linusghanadan.github.io/\n    affiliation: MEDS\n    affiliation-url: https://bren.ucsb.edu/masters-programs/master-environmental-data-science\ndate: 03-11-2024\ncategories:\n  - [Statistical Modeling]\n  - [Causal Inference]\n  - [R]\ncitation:\n  url: https://linusghanadan.github.io/blog/2024-3-11-post/\ndraft: false\nformat:\n    html:\n        code-fold: true\n---\n\n\n\n\n#### **Disclaimer: The data used in this blog was synthetically generated for an assignment in my Master's program class on Environmental Policy Evaluation (i.e., data is fake so results have no real implications).**\n\n## [Link to GitHub repository](https://github.com/linusghanadan/catch-shares-policy)\n\n## Question\n\nFrom 1990 to 2012, what was the average treatment effect on the treated (ATT) and average treatment effect (ATE) of implementing an Individual Transferable Quota (ITQ) on the share of years that a fishery was collapsed? For our purposes, \"collapsed\" is defined as harvest being more than 10% below maximum recorded harvest.\n\n## Background\n\nAccording to a [2020 article](https://www.sciencedirect.com/science/article/pii/S0308597X1930346X) published in the journal Marine Policy, Individual Transferable Quotas (ITQs) involve the allocation of shares or portions of a total allowable catch (TAC) to individual fishers, vessels, communities or others with an interest in the fishery, such as processors. A number of fisheries around the world have introduced ITQs as a way to regulate fisheries in a sustainable manner, preserving important natural resources while also allowing for increased economic productivity.\n\n## Data\n\nWe will use synthetically generated data to simplify things for our purposes (i.e., our data is fake so our results will have no real implications). Our data contains the variables on 11,135 hypothetical fisheries (only cross sectional, no time observations). These fisheries were either regulated by an Individual Transferable Quota (ITQ) for all years between 1990 and 2012 or in none of those years.\n\n**The outcome and treatment variables are:**\n\n- **COLL_SHARE** = share of years a fishery is collapsed between 1990 and 2012 (collapse defined as harvest being more than 10% below maximum recorded harvest).\n\n- **ITQ** = dummy variable indicating ‘treatment’ with an ITQ (equal to 1 if the fishery has been regulated by an ITQ and 0 otherwise). \n\n**The control variables are:**\n\n- **MET1, MET2, ….MET6** = Dummy variables indicating to which Marine Ecosystem Type (MET) the fishery belongs to (coral reefs, kelp forests, seagrass meadows, open ocean, deep sea, mangrove forests). This type does not change over the relevant time period and does not depend on human influence.\n\n- **IND_SR** = Index of species richness in 1980 with values between 0 and 100 indicating the biodiversity with respect to species in the fishery. Bounds of 0 and 100 are the lowest and highest observed values of species diversity across all fisheries in 1980, respectively.\n\n- **COMM_VAL** = Commercial value of fisheries in 1980 in million US-$\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import packages\nlibrary(tidyverse)\nlibrary(plm)\nlibrary(lmtest)\nlibrary(estimatr)\nlibrary(Hmisc)\nlibrary(RItools)\nlibrary(MatchIt)\nlibrary(knitr)\nlibrary(kableExtra)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Load Data\nfisheries_df <- read.csv(here::here(\"data\", \"2024-3-11-post-data\", \"final_fisheries_data.csv\"))\n\n## Prepare Data\n# Change all column names to lowercase\ncolnames(fisheries_df) <- tolower(colnames(fisheries_df))\n```\n:::\n\n\n## Comparison of pre-treatment ecosystem characteristics in the treatment and control groups\n\n#### Marine Ecosystem Type (MET)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create MET column\nfisheries_df <- fisheries_df %>%\n  mutate(met = case_when(\n    met1 == 1 ~ 1,\n    met2 == 1 ~ 2,\n    met3 == 1 ~ 3,\n    met4 == 1 ~ 4,\n    met5 == 1 ~ 5,\n    met6 == 1 ~ 6))\n\n# Convert MET to factors\nfisheries_df$met <- as.factor(fisheries_df$met)\n\n# Aggregate data and negate count for control\nfisheries_summary <- fisheries_df %>%\n  count(met, itq) %>%\n  spread(key = itq, value = n) %>%\n  gather(key = itq, value = 'count', -met) %>% \n  mutate(count = if_else(itq == '0', -count, count))\n\n# Create histograms\nggplot(fisheries_summary, aes(x = met, y = count, fill = as.factor(itq))) +\n  geom_col() +\n  scale_y_continuous(labels = function(x) abs(x), limits = c(-2000, 2000)) +\n  coord_flip() +\n  labs(title = \"Covariates comparison\", x = \"MET\", y = \"Count\") +\n  scale_fill_brewer(palette = \"Set2\", name = \"ITQ\",\n                    labels = c(\"0\" = \"control\", \"1\" = \"treatment\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nCompared to fisheries in the control group (not regulated by an ITQ), fisheries in the treatment group (regulated by an ITQ) were less likely to be coral reefs or mangrove forests and more likely to be kelp forests, seagrass meadows, open ocean, or deep sea (these differences are particularly pronounced for open ocean and deep sea).\n\n#### Species Richness Index\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean difference for IND_SR\nmean_diff_ind_sr <- mean(fisheries_df$ind_sr[fisheries_df$itq == 1]) - mean(fisheries_df$ind_sr[fisheries_df$itq == 0])\nmean_diff_ind_sr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -8.825477\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean difference t-test for IND_SR\nt.test(ind_sr ~ itq, data = fisheries_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  ind_sr by itq\nt = 41.826, df = 10839, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n 8.411868 9.239086\nsample estimates:\nmean in group 0 mean in group 1 \n       57.38515        48.55968 \n```\n:::\n:::\n\n\nFor species richness (SR) index in 1980, we reject the null hypothesis, at an alpha level of <0.001, that the difference in the mean SR index between the control (not regulated by an ITQ) and treatment (regulated by an ITQ) groups is zero. We estimate this mean difference to be about 8.83 index units (where the mean SR index is lower in the treatment group), and our 95% confidence interval for the mean difference is from 8.41 to 9.24 index units.\n\n#### Commercial value\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean difference for COMM_VAL\nmean_diff_comm_val <- mean(fisheries_df$comm_val[fisheries_df$itq == 1]) - mean(fisheries_df$comm_val[fisheries_df$itq == 0])\nmean_diff_comm_val\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -32.34931\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean difference t-test for COMM_VAL\nt.test(comm_val ~ itq, data = fisheries_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  comm_val by itq\nt = 39.507, df = 9334.9, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n 30.74425 33.95437\nsample estimates:\nmean in group 0 mean in group 1 \n      117.22839        84.87908 \n```\n:::\n:::\n\n\nRegarding the commercial value of fisheries in 1980, we also reject the null hypothesis, at an alpha level of <0.001, that the difference in the mean SR index between the control (not regulated by an ITQ) and treatment (regulated by an ITQ) groups is zero. We estimate this mean difference to be about 32.35 million USD (where the mean commercial value is lower in the treatment group), and our 95% confidence interval for the mean difference is from 30.74 to 33.95 million USD.\n\n#### Findings\n\nFor two of the covariates (SR index and commercial value), there are statistically significant differences between the treated and untreated groups. This indicates that there may be systemic differences between the pre-treatment ecosystem characteristics of fisheries that were regulated by an ITQ and those that were not, and if this is the case, simply controlling for all covariates is an insufficient method to estimate the ATE, since systemic differences means that there are differences between the groups that extend beyond what we can control for.\n\nBecause there seem to be systemic differences between the pre-treatment characteristics of the treated and untreated group, we will use the nearest neighbor matching estimator to estimate the ATT and the Weighted Least Squares (WLS) estimator to estimate the ATE.\n\n## Estimating propensity scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimation of propensity scores with the glm function and logit model\nps_reg <- glm(itq ~ met1 + met2 + met3 + met4 + met5 + ind_sr + comm_val,\n          data = fisheries_df, family = binomial())\n\n# Attach the predicted propensity score to the data frame\nfisheries_df$psvalue <- predict(ps_reg, type    = \"response\")\n\n# Drawing back to back histograms for propensity scores for treated and non-treated before matching\nhistbackback(split(fisheries_df$psvalue, fisheries_df$itq),\n             main = \"Propensity score before matching\", xlab = c(\"control\", \"treatment\"), xlim = c(-600, 800))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThere is some overlap in the distributions of our histograms, mainly for fisheries that have propensity scores between 0.4 and 0.6. I’m concerned about the lack of overlap for fisheries with high propensity scores, as this may lead to issues when we do nearest-neighbor matching. During nearest-neighbor matching, treated units are assigned to the non-treated unit with the closest propensity score as a match, and we want the resulting set of fisheries to have a great deal of overlap in their propensity scores to ensure a balance in covariates, since they are also likely to have an influence on our outcome variable. However, since there are very few fisheries in the control group with high propensity scores, I’m concerned that even after nearest-neighbor matching occurs, there will still be a lack of overlap in the distributions of our histograms.\n\n## Estimating ATT with nearest neighbor matching estimator\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Nearest Neighbor Matching\n\n# Match using nearest-neighbor approach (treated units are assigned the non-treated unit with the closest propensity score as match)\nnn_matching <- matchit(itq ~ met1 + met2 + met3 + met4 + met5 + ind_sr + comm_val,\n                       data = fisheries_df, method = \"nearest\", ratio = 1)\nmatch_data = match.data(nn_matching)\n\n## Estimate ATT\n\n# Calculate sum of the differences of outcomes between matches\nsumdiff_data <- match_data %>%\n  group_by(subclass) %>%\n  mutate(diff = coll_share[itq==1] - coll_share[itq==0])\nsumdiff <- sum(sumdiff_data$diff)/2\n\n# Divide sum of the difference by the number treated to generate ATT estimate\nATT_nn = sumdiff / sum(match_data$itq)\nATT_nn\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.07132623\n```\n:::\n:::\n\n\nUsing the matched data, we estimate the average effect of an ITQ on a fishery that had an ITQ to be a 7.13 percentage-point decrease in the share of years between 1990 and 2012 where the fishery experienced collapse. This estimated effect size only applies to fisheries that were regulated by an ITQ because we only defined counterfactuals for these fisheries. Thus, our average outcome only demonstrates the effect of an ITQ on fishery collapse as it pertains to fisheries that were regulated by an ITQ.\n\n## Calculating ATE with the WLS estimator\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## WLS Matching\n\n# calculation of the weights (see slide 25 of lecture 5)\nPS <- fisheries_df$psvalue\nD <- fisheries_df$itq\n\n# add weights to data frame\nfisheries_df$wgt = (D/PS + (1-D)/(1-PS))\n\n# run WLS regression\nreg_wls <- lm(coll_share ~ itq + met1 + met2 + met3 + met4 + met5 + ind_sr + comm_val,\n               data = fisheries_df, weights = wgt)\n\n## Estimate ATE\n\n# Extracting the coefficients table\nsummary_reg <- summary(reg_wls)\nsummary_reg$coefficients %>% \n  kbl(caption = \"WLS estimator\") %>%  # Generate table\n  kable_classic(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic\" style='font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n<caption>WLS estimator</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> t value </th>\n   <th style=\"text-align:right;\"> Pr(&gt;|t|) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 0.3748451 </td>\n   <td style=\"text-align:right;\"> 0.0030280 </td>\n   <td style=\"text-align:right;\"> 123.79136 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> itq </td>\n   <td style=\"text-align:right;\"> -0.0766783 </td>\n   <td style=\"text-align:right;\"> 0.0009902 </td>\n   <td style=\"text-align:right;\"> -77.43563 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> met1 </td>\n   <td style=\"text-align:right;\"> -0.1119518 </td>\n   <td style=\"text-align:right;\"> 0.0019244 </td>\n   <td style=\"text-align:right;\"> -58.17396 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> met2 </td>\n   <td style=\"text-align:right;\"> -0.1285996 </td>\n   <td style=\"text-align:right;\"> 0.0022096 </td>\n   <td style=\"text-align:right;\"> -58.20071 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> met3 </td>\n   <td style=\"text-align:right;\"> -0.0968933 </td>\n   <td style=\"text-align:right;\"> 0.0018096 </td>\n   <td style=\"text-align:right;\"> -53.54421 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> met4 </td>\n   <td style=\"text-align:right;\"> -0.0634837 </td>\n   <td style=\"text-align:right;\"> 0.0022391 </td>\n   <td style=\"text-align:right;\"> -28.35257 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> met5 </td>\n   <td style=\"text-align:right;\"> -0.0323470 </td>\n   <td style=\"text-align:right;\"> 0.0019230 </td>\n   <td style=\"text-align:right;\"> -16.82119 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ind_sr </td>\n   <td style=\"text-align:right;\"> -0.0014749 </td>\n   <td style=\"text-align:right;\"> 0.0000412 </td>\n   <td style=\"text-align:right;\"> -35.80433 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> comm_val </td>\n   <td style=\"text-align:right;\"> 0.0003786 </td>\n   <td style=\"text-align:right;\"> 0.0000112 </td>\n   <td style=\"text-align:right;\"> 33.94403 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nUsing the WLS estimator, we estimate the average effect of an ITQ on a fishery to be a 7.67 percentage-point decrease in the share of years between 1990 and 2012 where the fishery experienced collapse, with a standard error of 0.099 percentage-points. The very low p-value means we reject the null hypothesis that the average effect of an ITQ is zero at an alpha level of <0.001. Our estimated effect size, as calculated here, applies to all fisheries because we did not remove any fisheries from our sample, like we did when estimating effect size based on matching.\n\n## Conclusion\n\nOur comparison of pre-treatment ecosystem characteristics showed that fisheries regulated with an ITQ between 1990 and 2012 had significant differences in Species Richness Index and commercial value compared to ones not regulated by an ITQ. For this reason, the treatment ignorability seemed like it would be a bad assumption to make, so we estimated propensity scores in order to calculate ATT using Nearest Neighbor Matching and ATE using the WLS estimator.\n\nUsing the matched data, we estimated the ATT to be a 7.13 percentage-point decrease in the share of years between 1990 and 2012 where the fishery experienced collapse. Then, using the WLS estimator, we estimated the ATE to be a 7.67 percentage-point decrease in the share of years between 1990 and 2012 where the fishery experienced collapse, with a standard error of 0.099 percentage-points.\n\nOverall, our most useful finding here is the very low standard error when estimating ATE with the WLS estimator, indicating that we are 95% confident that the true ATE is between a 7.57 and 7.77 percentage-point decrease in share of years with a fishery collapse. In addition, the very low p-value corresponding to the low standard error means we reject the null hypothesis that the average effect of an ITQ is zero at an alpha level of <0.001.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}